name: Lint and Test

on:
  push:
    branches: [main, v*.*]
  pull_request:
    branches: [main, v*.*]

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: "1.9.1"
  RUST_TOOLCHAIN: nightly-2021-12-15

defaults:
  run:
    working-directory: ./

jobs:
  lint:
    name: Run ftm and clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Run fmt
        run: cargo fmt -- --check
      # The style and complexity lints have not been processed yet.
      - name: Run clippy
        run: cargo clippy -- --deny=warnings --allow=clippy::style --allow=clippy::complexity

  tests:
    name: Run tests and Soteria
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      # Install Solana
      - name: Cache Solana binaries
        uses: actions/cache@v2
        with:
          path: ~/.cache/solana
          key: ${{ runner.os }}-${{ env.SOLANA_VERSION }}
      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          echo "Generating keypair..."
          solana-keygen new -o "$HOME/.config/solana/id.json" --no-passphrase --silent

      - name: Run unit tests
        run: cargo test --lib
      - name: Build program
        run: cargo build-bpf
      - name: Run tests
        run: cargo test-bpf

      # Create a cache for Soteria
      - name: Cache Soteria
        id: cache-soteria
        uses: actions/cache@v2
        with:
          path: ~/.cache/soteria
          key: ${{ runner.os }}-soteria
          
      # Install Soteria
      - name: Install Soteria
        run: |
          echo "Downloading Soteria..."
          sh -c "$(curl -k https://supercompiler.xyz/install)"
          export PATH=$PWD/soteria-linux-develop/bin/:$PATH
          echo "$PWD/soteria-linux-develop/bin" >> $GITHUB_PATH
          echo "Updating Rust..."
          rustup update
          echo "Soteria ready!"
          
      # Run Soteria tests against Cargo.toml for this repo (root folder)
      - name: Run Soteria
        run: |
          echo "Running Soteria..."
          soteria -analyzeAll .
          echo "Soteria finished!"
